#!/bin/bash

for i in {1..400} #34
do
    wget -w 1 --random-wait -O $i.html "http://www.p2000-online.net/p2000.php?Haaglanden=1&RotterdamRijnmond=1&Brandweer=1&Pagina=$i"
    grep -E "class=\"Md|class=\"Mdx" $i.html >> events.txt
done
